# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
image: gradle:alpine

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
stages:
  - clean
  - prepare
  - build
  - test
  - deploy

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`.gradle

clean:
  stage: clean
  script: gradle clean
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
  tags:
    - gradle
doc:
  stage: prepare
  script:
    - cd sirius_doc
    - gradle buildDoku
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
  tags:
    - artifactory
    - gradle
    - biber-latex
#build:
#  stage: build
#  script: gradle --build-cache assemble
#  cache:
#    key: "$CI_COMMIT_REF_NAME"
#    policy: push
#    paths:
#      - build
#      - .gradle
#
#test:
#  stage: test
#  script: gradle check
#  cache:
#    key: "$CI_COMMIT_REF_NAME"
#    policy: pull
#    paths:
#      - build
#      - .gradle
