name: Release Hashes

on:
  release:
    types: [published, edited]

jobs:
  hashes:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Release Hashes
        uses: MCJack123/ghaction-Generate-Release-Hashes@v2
        with:
          hash-type: sha256
          file-name: sha256.txt

      - name: Generate Release Hashe
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # The URL for uploading assets to the release
          upload_url: ${{ github.event.release.upload_url }}
          # The path to the asset you want to upload
          asset_path: sha256.txt
          # The name of the asset you want to upload
          asset_name: sha256-hashes.txt
          # The content-type of the asset you want to upload. See the supported Media Types here: https://www.iana.org/assignments/media-types/media-types.xhtml for more information
          asset_content_type: text/plain